// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WNZland.Data;

#nullable disable

namespace WNZland.Migrations
{
    [DbContext(typeof(WNZDbContext))]
    [Migration("20250211185605_seedingComplete")]
    partial class seedingComplete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WNZland.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6db438f6-9747-4be6-8e62-8c34957719e1"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("67b2151d-b948-4a32-ab60-f8cbf48b1349"),
                            Name = "Moderate"
                        },
                        new
                        {
                            Id = new Guid("1ed5deec-7b0c-441a-a7ea-a67d11864f77"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("WNZland.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6db438f6-9747-4be6-8e62-8c34957719e3"),
                            Code = "N",
                            Name = "Northland",
                            RegionImageUrl = "https://www.wnz.org.nz/wp-content/uploads/2021/06/Te-Henga-Walkway-1.jpg"
                        },
                        new
                        {
                            Id = new Guid("67b2151d-b948-4a32-ab60-f8cbf48b1343"),
                            Code = "A",
                            Name = "Auckland",
                            RegionImageUrl = "https://www.wnz.org.nz/wp-content/uploads/2021/06/Te-Henga-Walkway-2.jpg"
                        },
                        new
                        {
                            Id = new Guid("1ed5deec-7b0c-441a-a7ea-a67d11864f73"),
                            Code = "W",
                            Name = "Waikato",
                            RegionImageUrl = "https://www.wnz.org.nz/wp-content/uploads/2021/06/Te-Henga-Walkway-3.jpg"
                        });
                });

            modelBuilder.Entity("WNZland.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInkm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("WNZland.Models.Domain.Walk", b =>
                {
                    b.HasOne("WNZland.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WNZland.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
